# backend/scripts/generate_pixel_icons.py
# Generador de 32 Iconos Pixel Art 16x16 para Code Quest: Reino de Java
# Produce PNGs optimizados con canal alfa transparente sin dependencias externas

import os
import struct
import zlib

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), '..', '..', 'frontend', 'assets', 'icons')
os.makedirs(OUTPUT_DIR, exist_ok=True)

def create_png(width, height, rgba_pixels):
    """Genera un archivo PNG válido en bytes a partir de un arreglo RGBA."""
    header = b'\x89PNG\r\n\x1a\n'
    ihdr_data = struct.pack('>IIBBBBB', width, height, 8, 6, 0, 0, 0)
    ihdr_crc = struct.pack('>I', zlib.crc32(b'IHDR' + ihdr_data))
    ihdr = struct.pack('>I', len(ihdr_data)) + b'IHDR' + ihdr_data + ihdr_crc
    
    raw = bytearray()
    for y in range(height):
        raw.append(0) # Filtro None
        for x in range(width):
            raw.extend(rgba_pixels[y * width + x])
            
    idat_data = zlib.compress(bytes(raw), 9)
    idat_crc = struct.pack('>I', zlib.crc32(b'IDAT' + idat_data))
    idat = struct.pack('>I', len(idat_data)) + b'IDAT' + idat_data + idat_crc
    
    iend = struct.pack('>I', 0) + b'IEND' + struct.pack('>I', zlib.crc32(b'IEND'))
    return header + ihdr + idat + iend

def grid_to_rgba(grid_str, palette):
    """Convierte una cuadrícula ASCII de 16x16 a arreglo RGBA usando una paleta."""
    lines = [l.strip() for l in grid_str.strip().split('\n') if l.strip()]
    assert len(lines) == 16, f"Se esperaban 16 líneas, se recibieron {len(lines)}"
    pixels = []
    for y, line in enumerate(lines):
        assert len(line) == 16, f"Línea {y} tiene longitud {len(line)}, se esperaban 16"
        for char in line:
            color = palette.get(char, (0, 0, 0, 0))
            pixels.append(color)
    return pixels

def save_icon(name, grid_str, palette):
    pixels = grid_to_rgba(grid_str, palette)
    png_bytes = create_png(16, 16, pixels)
    path = os.path.join(OUTPUT_DIR, f"{name}.png")
    with open(path, 'wb') as f:
        f.write(png_bytes)
    print(f"  ✨ Creado: {name}.png ({len(png_bytes)} bytes)")

print("\n🎨 Generando Colección Oficial de Iconos Pixel Art de Code Quest...")

# ==============================================================================
# 1. CORAZÓN LLENO (Vida activa del héroe)
# ==============================================================================
save_icon('corazon_lleno', """
................
..OOOO....OOOO..
.OHHFFO..OFFFFO.
.OHFFFFOOFFFFFO.
.OFFFFFFFFFFFFF.
.OFFFFFFFFFFFFF.
.OFFFFFFFFFFFFO.
..OFFFFFFFFFFFO.
...OFFFFFFFFFFO.
....OFFFFFFFFO..
.....OFFFFFFO...
......OFFFFO....
.......OFFO.....
........OO......
................
................
""", {
    '.': (0, 0, 0, 0),
    'O': (127, 29, 29, 255),  # Crimson oscuro
    'H': (254, 202, 202, 255), # Reflejo blanco/rosa
    'F': (239, 68, 68, 255),   # Rojo brillante
})

# ==============================================================================
# 2. CORAZÓN VACÍO (Salud perdida / contenedor de piedra)
# ==============================================================================
save_icon('corazon_vacio', """
................
..OOOO....OOOO..
.OHHFFO..OFFFFO.
.OHFFFFOOFFFFFO.
.OFFFFFFFFFFFFF.
.OFFFFFFFFFFFFF.
.OFFFFFFFFFFFFO.
..OFFFFFFFFFFFO.
...OFFFFFFFFFFO.
....OFFFFFFFFO..
.....OFFFFFFO...
......OFFFFO....
.......OFFO.....
........OO......
................
................
""", {
    '.': (0, 0, 0, 0),
    'O': (15, 23, 42, 255),   # Borde carbón
    'H': (71, 85, 105, 255),  # Brillo gris piedra
    'F': (30, 41, 59, 255),   # Relleno gris oscuro
})

# ==============================================================================
# 3. ESPADA (Ataque y fuerza del guerrero)
# ==============================================================================
save_icon('espada', """
.............HO.
............HFO.
...........HFFO.
..........HFFO..
.........HFFO...
........HFFO....
.......HFFO.....
..GG..HFFO......
.GSSG..OO.......
..GGSSGH........
...GGSSG........
....GGSSG.......
.....GGSSG......
......GSSG......
.......GG.......
................
""", {
    '.': (0, 0, 0, 0),
    'H': (255, 255, 255, 255), # Filo brillante
    'F': (203, 213, 225, 255), # Acero pulido
    'O': (71, 85, 105, 255),   # Sombra de hoja
    'G': (245, 158, 11, 255),  # Guarda y pomo dorados
    'S': (120, 53, 15, 255),   # Empuñadura de cuero
})

# ==============================================================================
# 4. ESCUDO (Defensa y placa del héroe)
# ==============================================================================
save_icon('escudo', """
...GGGGGGGGGG...
..GBBBBBBBBBBG..
..GBWWBBBBWWBG..
..GBWWBBBBWWBG..
..GBWWWWWWWWBG..
..GBWWWWWWWWBG..
..GBWWBBBBWWBG..
..GBWWBBBBWWBG..
...GBBBBBBBBG...
...GBBBBBBBBG...
....GBBBBBBG....
....GBBBBBBG....
.....GBBBBG.....
......GBBG......
.......GG.......
................
""", {
    '.': (0, 0, 0, 0),
    'G': (245, 158, 11, 255),  # Borde dorado
    'B': (37, 99, 235, 255),   # Campo azul zafiro
    'W': (254, 240, 138, 255), # Cruz dorada central
})

# ==============================================================================
# 5. POCIÓN CURATIVA (Poción mágica en matraz de cristal)
# ==============================================================================
save_icon('pocion', """
......CCCC......
......CCCC......
.....GGGGGG.....
.....G....G.....
....GG....GG....
...GPPWPPPPPG...
..GPPPPPPPPPPG..
..GPPPWPPPPPPG..
..GPPPPPPPPPPG..
..GPPPPPPPPPPG..
..GPPPPPPPPPPG..
...GPPPPPPPPG...
....GGGGGGGG....
................
................
................
""", {
    '.': (0, 0, 0, 0),
    'C': (146, 64, 14, 255),   # Tapón de corcho
    'G': (148, 163, 184, 255), # Vidrio de cristal
    'P': (236, 72, 153, 255),  # Elixir carmesí/magenta
    'W': (255, 255, 255, 255), # Burbujas y brillo
})

# ==============================================================================
# 6. LLAVE DE MAZMORRA (Llave maestra dorada)
# ==============================================================================
save_icon('llave', """
....GGGG........
...GWWWWG.......
..GWG..GWG......
..GWG..GWG......
...GWWWWG.......
....GGGG........
.....GWG........
.....GWG........
.....GWGGG......
.....GWGGG......
.....GWG........
.....GWGGG......
.....GWGGG......
.....GWG........
.....GGG........
................
""", {
    '.': (0, 0, 0, 0),
    'G': (180, 83, 9, 255),    # Borde bronce/oro
    'W': (251, 191, 36, 255),  # Oro brillante
})

# ==============================================================================
# 7. ESTRELLA (Puntos de experiencia)
# ==============================================================================
save_icon('estrella', """
.......OO.......
.......OY.......
......OYYO......
......OYYO......
.OOOOOOYYYYOOOO.
..OYYYYYYYYYYO..
...OYYYYYYYYO...
....OYYYYYYO....
...OYYYYYYYYO...
..OYYYYO.OYYYO..
.OYYYO.....OYYO.
.OYYO.......OYYO
.OO...........OO
................
................
................
""", {
    '.': (0, 0, 0, 0),
    'O': (180, 83, 9, 255),    # Contorno ámbar
    'Y': (253, 224, 71, 255),  # Oro amarillo fulgurante
})

# ==============================================================================
# 8. OBJETIVO / DIANA (Próximo jefe)
# ==============================================================================
save_icon('objetivo', """
.....GG..GG.....
....RRRRRRRR....
...RWWWWWWWWR...
..RWWRRRRRRWWR..
..RWRRWWWWWRWR..
.GRWRWWYYWWRWRG.
.GRWRWYRRYWRWRG.
.GRWRWYRRYWRWRG.
.GRWRWWYYWWRWRG.
..RWRRWWWWWRWR..
..RWWRRRRRRWWR..
...RWWWWWWWWR...
....RRRRRRRR....
.....GG..GG.....
................
................
""", {
    '.': (0, 0, 0, 0),
    'G': (245, 158, 11, 255),  # Marcador exterior dorado
    'R': (220, 38, 38, 255),   # Anillos rojos
    'W': (248, 250, 252, 255), # Anillo blanco
    'Y': (251, 191, 36, 255),  # Centro dorado
})

# ==============================================================================
# 9. CANDADO (Zonas y cofres bloqueados)
# ==============================================================================
save_icon('candado', """
.....SSSSSS.....
....S......S....
....S......S....
....S......S....
...GGGGGGGGGG...
...GWWWWWWWWG...
...GWWWWWWWWG...
...GWWWKKWWWG...
...GWWKKKKWWG...
...GWWWKKWWWG...
...GWWWKKWWWG...
...GWWWWWWWWG...
...GGGGGGGGGG...
................
................
................
""", {
    '.': (0, 0, 0, 0),
    'S': (148, 163, 184, 255), # Arco de acero
    'G': (180, 83, 9, 255),    # Borde de latón
    'W': (245, 158, 11, 255),  # Cuerpo dorado
    'K': (15, 23, 42, 255),    # Agujero de cerradura
})

# ==============================================================================
# 10. CORONA (Gran Maestro Java / Administrador)
# ==============================================================================
save_icon('corona', """
................
..W..........W..
..GW...WW...WG..
..GGW.GWWG.WGG..
..GGGWWGGWWGGG..
..GGGGGGGGGGGG..
..GRGGGEGGGGBG..
..GGGGGGGGGGGG..
..WWWWWWWWWWWW..
..GGGGGGGGGGGG..
................
................
................
................
................
................
""", {
    '.': (0, 0, 0, 0),
    'W': (254, 240, 138, 255), # Puntas y brillo oro
    'G': (245, 158, 11, 255),  # Oro real
    'R': (239, 68, 68, 255),   # Rubí
    'E': (16, 185, 129, 255),  # Esmeralda
    'B': (59, 130, 246, 255),  # Zafiro
})

# ==============================================================================
# 11. ESPADAS CRUZADAS (Combate y acción)
# ==============================================================================
save_icon('espadas_cruzadas', """
.WW..........WW.
.WSSW......WSSW.
..WSSW....WSSW..
...WSSW..WSSW...
....WSSWWSSW....
.....WSSSSW.....
......WSSW......
.....GGWWGG.....
....GSSGGSSG....
...GSSG..GSSG...
..GSSG....GSSG..
..GG........GG..
................
................
................
................
""", {
    '.': (0, 0, 0, 0),
    'W': (248, 250, 252, 255), # Hojas de acero
    'S': (148, 163, 184, 255), # Sombra de metal
    'G': (245, 158, 11, 255),  # Guardas doradas
})

# ==============================================================================
# 12. SONIDO ON (Audio activo)
# ==============================================================================
save_icon('sonido_on', """
................
...WW...........
..WBBW...CC.....
.WBBBBW...CC....
.WBBBBW....CC...
.WBBBBW.....CC..
.WWWWWW.....CC..
...WW.......CC..
............CC..
...WW.......CC..
.WWWWWW.....CC..
.WBBBBW.....CC..
.WBBBBW....CC...
.WBBBBW...CC....
..WBBW...CC.....
...WW...........
""", {
    '.': (0, 0, 0, 0),
    'W': (245, 158, 11, 255),  # Altavoz dorado
    'B': (180, 83, 9, 255),    # Cono interior
    'C': (56, 189, 248, 255),  # Ondas de sonido celestes
})

# ==============================================================================
# 13. SONIDO OFF (Audio silenciado)
# ==============================================================================
save_icon('sonido_off', """
R...............
.RW.............
..RWW...........
.W.RBBW..R......
.WB.RBBW..R.....
.WBB.RBBW..R....
.WWWW.RWW...R...
...WW..R.....R..
........R.....R.
...WW....R.....R
.WWWWWW...R.....
.WBBBBW....R....
.WBBBBW.....R...
.WBBBBW......R..
..WBBW........R.
...WW..........R
""", {
    '.': (0, 0, 0, 0),
    'W': (148, 163, 184, 255), # Altavoz gris
    'B': (71, 85, 105, 255),
    'R': (239, 68, 68, 255),   # Barra de mute roja
})

# ==============================================================================
# 14. PAUSA (Botón de pausa)
# ==============================================================================
save_icon('pausa', """
..GGGGGGGGGGGG..
.GGWWWWWWWWWWGG.
.GWWWWWWWWWWWWG.
.GWWGGWWWWGGWWG.
.GWWGGWWWWGGWWG.
.GWWGGWWWWGGWWG.
.GWWGGWWWWGGWWG.
.GWWGGWWWWGGWWG.
.GWWGGWWWWGGWWG.
.GWWGGWWWWGGWWG.
.GWWWWWWWWWWWWG.
.GGWWWWWWWWWWGG.
..GGGGGGGGGGGG..
................
................
................
""", {
    '.': (0, 0, 0, 0),
    'G': (180, 83, 9, 255),    # Borde ámbar
    'W': (251, 191, 36, 255),  # Oro brillante
})

# ==============================================================================
# 15. PLAY (Continuar / Reanudar)
# ==============================================================================
save_icon('play', """
..GGGG..........
..GGWWGG........
..GGWWWWGG......
..GGWWWWWWGG....
..GGWWWWWWWWGG..
..GGWWWWWWWWWWG.
..GGWWWWWWWWWWWG
..GGWWWWWWWWWWWG
..GGWWWWWWWWWWG.
..GGWWWWWWWWGG..
..GGWWWWWWGG....
..GGWWWWGG......
..GGWWGG........
..GGGG..........
................
................
""", {
    '.': (0, 0, 0, 0),
    'G': (21, 128, 61, 255),   # Borde verde esmeralda
    'W': (74, 222, 128, 255),  # Verde brillante
})

# ==============================================================================
# 16. TROFEO (Salón de la Fama / Ranking)
# ==============================================================================
save_icon('trofeo', """
.WWWWWWWWWWWWWW.
.GWWWWWWWWWWWWG.
GW.GWWWWWWWWG.WG
GW..GWWWWWWG..WG
GW...GWWWWG...WG
.G....GWWG....G.
.......GG.......
.......GG.......
......GGGG......
......GGGG......
.....GGGGGG.....
.....GSSSSG.....
....GSSSSSSG....
....GGGGGGGG....
................
................
""", {
    '.': (0, 0, 0, 0),
    'W': (254, 240, 138, 255), # Brillo dorado
    'G': (245, 158, 11, 255),  # Oro del trofeo
    'S': (120, 53, 15, 255),   # Pedestal de madera noble
})

# ==============================================================================
# 17. MOCHILA (Inventario de aventurero)
# ==============================================================================
save_icon('mochila', """
.....BBBBBB.....
....BRRRRRRB....
...BBRRRRRRBB...
...BLLLLLLLLB...
...BLWLLLLWLB...
...BLLLLLLLLB...
..BLLLLLLLLLLB..
..BLLWLLLLWLLB..
..BLLWLLLLWLLB..
..BLLLLLLLLLLB..
..BLLLLLLLLLLB..
...BBBBBBBBBB...
................
................
................
................
""", {
    '.': (0, 0, 0, 0),
    'B': (69, 26, 3, 255),     # Cuero oscuro
    'R': (220, 38, 38, 255),   # Saco de dormir enrollado
    'L': (180, 83, 9, 255),    # Cuero teñido
    'W': (251, 191, 36, 255),  # Hebillas de bronce
})

# ==============================================================================
# 18. PERGAMINO (Historia / Lore)
# ==============================================================================
save_icon('pergamino', """
..PPPP..........
.PWWWWP.........
.PWWWWRRP.......
.PWWWWWWRP......
.PWWWWWWWRP.....
.PWWWWWWWWRP....
..PWWWWWWWRP....
...PWWWWWWRP....
....PWWWWWRP....
.....PWWWWRP....
......PWWWRP....
.......PRRRP....
........PWWWWP..
.........PPPP...
................
................
""", {
    '.': (0, 0, 0, 0),
    'P': (180, 83, 9, 255),    # Bordes dorados
    'W': (254, 243, 199, 255), # Papiro envejecido
    'R': (220, 38, 38, 255),   # Cinta de cera carmesí
})

# ==============================================================================
# 19. LIBRO (Explicación didáctica de Java)
# ==============================================================================
save_icon('libro', """
...GGGGGGGGGG...
..GWWWWWWWWWWG..
.GWWPPPPPPPPWWG.
.GWWPRRRRRRPWWG.
.GWWPRRRRRRPWWG.
.GWWPRRRRRRPWWG.
.GWWPRRRRRRPWWG.
.GWWPRRRRRRPWWG.
.GWWPPPPPPPPWWG.
.GWWWWWWWWWWWWG.
..GGGGGGGGGGGG..
................
................
................
................
................
""", {
    '.': (0, 0, 0, 0),
    'G': (109, 40, 217, 255),  # Cubierta púrpura
    'W': (248, 250, 252, 255), # Páginas
    'P': (245, 158, 11, 255),  # Filigrana de oro
    'R': (220, 38, 38, 255),   # Emblema central rojo
})

# ==============================================================================
# 20. PUERTA / SALIR (Menú Principal)
# ==============================================================================
save_icon('puerta', """
....SSSSSSSS....
...SLLLLLLLLS...
..SLLLLLLLLLLS..
..SLLLLLLLLLLS..
..SLLLLLLLLLLS..
..SLLLLLLLLLLS..
..SLLLLLLLLLLS..
..SLLLLWKLLLLS..
..SLLLLLLLLLLS..
..SLLLLLLLLLLS..
..SLLLLLLLLLLS..
..SLLLLLLLLLLS..
..SSSSSSSSSSSS..
................
................
................
""", {
    '.': (0, 0, 0, 0),
    'S': (71, 85, 105, 255),   # Marco de piedra
    'L': (120, 53, 15, 255),   # Tablones de roble
    'W': (251, 191, 36, 255),  # Manija dorada
    'K': (15, 23, 42, 255),    # Cerrojo
})

# ==============================================================================
# 21. CERRAR / EQUIS (Cerrar modales)
# ==============================================================================
save_icon('cerrar', """
..RRRRRRRRRRRR..
.RRWWWWWWWWWWRR.
.RWW........WWR.
.RW.WW....WW.WR.
.RW..WW..WW..WR.
.RW...WWWW...WR.
.RW....WW....WR.
.RW...WWWW...WR.
.RW..WW..WW..WR.
.RW.WW....WW.WR.
.RWW........WWR.
.RRWWWWWWWWWWRR.
..RRRRRRRRRRRR..
................
................
................
""", {
    '.': (0, 0, 0, 0),
    'R': (153, 27, 27, 255),   # Borde rojo oscuro
    'W': (255, 255, 255, 255), # Cruz blanca
})

# ==============================================================================
# 22. CHECK VERDE (Respuesta correcta)
# ==============================================================================
save_icon('check_verde', """
..GGGGGGGGGGGG..
.GG..........GG.
.G............G.
.G.........WW.G.
.G........WWW.G.
.G.......WWWW.G.
.G..WW..WWWW..G.
.G..WWWWWWW...G.
.G...WWWWW....G.
.G....WWW.....G.
.G.....W......G.
.GG..........GG.
..GGGGGGGGGGGG..
................
................
................
""", {
    '.': (0, 0, 0, 0),
    'G': (22, 163, 74, 255),   # Círculo verde
    'W': (255, 255, 255, 255), # Check blanco
})

# ==============================================================================
# 23. ERROR ROJO (Respuesta incorrecta)
# ==============================================================================
save_icon('error_rojo', """
..RRRRRRRRRRRR..
.RR..........RR.
.R..WW....WW..R.
.R...WW..WW...R.
.R....WWWW....R.
.R.....WW.....R.
.R....WWWW....R.
.R...WW..WW...R.
.R..WW....WW..R.
.RR..........RR.
..RRRRRRRRRRRR..
................
................
................
................
................
""", {
    '.': (0, 0, 0, 0),
    'R': (220, 38, 38, 255),   # Círculo carmesí
    'W': (255, 255, 255, 255), # 'X' blanca
})

# ==============================================================================
# 24. SABIO FOCO (Consejo y bombilla de ideas)
# ==============================================================================
save_icon('sabio_foco', """
.......YY.......
....Y..YY..Y....
.....YYYYYY.....
....YYYYYYYY....
....YYWWWWYY....
....YYYYYYYY....
.....YYYYYY.....
......GGGG......
......SSSS......
......SSSS......
.......SS.......
................
................
................
................
................
""", {
    '.': (0, 0, 0, 0),
    'Y': (250, 204, 21, 255),  # Luz dorada
    'W': (255, 255, 255, 255), # Filamento brillante
    'G': (180, 83, 9, 255),    # Base de bronce
    'S': (148, 163, 184, 255), # Rosca de metal
})

# ==============================================================================
# 25. ENCUESTA (Formulario de retroalimentación)
# ==============================================================================
save_icon('encuesta', """
.....BBBBBB.....
....BWWWWWWBB...
...BWWWWWWWWBB..
..BWWWWWWWWWWWB.
..BWBCCWWWWWWWB.
..BWWWWWWWWWWWB.
..BWBCCWWWWWWWB.
..BWWWWWWWWWWWB.
..BWBCCWWWWWWWB.
..BWWWWWWWWWWWB.
..BWWWWWWWWPPPB.
..BWWWWWWWPPPYB.
..BWWWWWWPPPPYB.
...BBBBBBBBBBBB.
................
................
""", {
    '.': (0, 0, 0, 0),
    'B': (120, 53, 15, 255),   # Tabla de madera
    'W': (248, 250, 252, 255), # Hoja de papel
    'C': (37, 99, 235, 255),   # Casillas marcadas
    'P': (245, 158, 11, 255),  # Lápiz
    'Y': (239, 68, 68, 255),   # Goma del lápiz
})

# ==============================================================================
# 26. MEDALLA DE ORO (Puesto #1)
# ==============================================================================
save_icon('medalla_oro', """
....RRR..RRR....
.....RR..RR.....
......RRRR......
.....GGGGGG.....
....GWWWWWWG....
...GW..WW..WG...
...G...WW...G...
...G...WW...G...
...G...WW...G...
...G...WW...G...
....GWWWWWWG....
.....GGGGGG.....
................
................
................
................
""", {
    '.': (0, 0, 0, 0),
    'R': (220, 38, 38, 255),   # Cinta roja
    'G': (180, 83, 9, 255),    # Borde oro
    'W': (251, 191, 36, 255),  # Medalla de oro brillante con número 1
})

# ==============================================================================
# 27. MEDALLA DE PLATA (Puesto #2)
# ==============================================================================
save_icon('medalla_plata', """
....BBB..BBB....
.....BB..BB.....
......BBBB......
.....SSSSSS.....
....SWWWWWWS....
...SW.WWWW.WS...
...S......W.S...
...S...WWWW.S...
...S..W.....S...
...S..WWWWW.S...
....SWWWWWWS....
.....SSSSSS.....
................
................
................
................
""", {
    '.': (0, 0, 0, 0),
    'B': (37, 99, 235, 255),   # Cinta azul
    'S': (100, 116, 139, 255), # Borde plata
    'W': (226, 232, 240, 255), # Medalla de plata con número 2
})

# ==============================================================================
# 28. MEDALLA DE BRONCE (Puesto #3)
# ==============================================================================
save_icon('medalla_bronce', """
....GGG..GGG....
.....GG..GG.....
......GGGG......
.....BBBBBB.....
....BWWWWWWB....
...BW.WWWW.WB...
...B......W.B...
...B...WWW..B...
...B......W.B...
...BW.WWWW.WB...
....BWWWWWWB....
.....BBBBBB.....
................
................
................
................
""", {
    '.': (0, 0, 0, 0),
    'G': (22, 101, 52, 255),   # Cinta verde bosque
    'B': (120, 53, 15, 255),   # Borde bronce
    'W': (217, 119, 6, 255),   # Medalla de bronce con número 3
})

# ==============================================================================
# 29. ALERTA (Advertencia triangular)
# ==============================================================================
save_icon('alerta', """
.......YY.......
......YYYY......
......YYYY......
.....YYKKYY.....
....YYYKKYYY....
....YYYKKYYY....
...YYYYKKYYYY...
...YYYYKKYYYY...
..YYYYYKKYYYYY..
..YYYYYYYYYYYY..
.YYYYYYKKYYYYYY.
.YYYYYYKKYYYYYY.
.YYYYYYYYYYYYYY.
.OOOOOOOOOOOOOO.
................
................
""", {
    '.': (0, 0, 0, 0),
    'O': (180, 83, 9, 255),    # Borde base ámbar
    'Y': (245, 158, 11, 255),  # Amarillo advertencia
    'K': (15, 23, 42, 255),    # Signo de exclamación negro
})

# ==============================================================================
# 30. REINICIAR (Flecha circular)
# ==============================================================================
save_icon('reiniciar', """
......CCCCC.....
....CC.....CC...
...C...CCC...C..
..C...CCCC....C.
.C...CCCCC.....C
.C...CC..C.....C
.C...C...C.....C
.C.......C.....C
.C.......C....C.
..C......C...C..
...C.....CCCC...
....CC.....C....
......CCCCC.....
................
................
................
""", {
    '.': (0, 0, 0, 0),
    'C': (56, 189, 248, 255),  # Flecha cyan brillante
})

# ==============================================================================
# 31. USUARIO (Casco de caballero)
# ==============================================================================
save_icon('usuario', """
.....SSSSSS.....
...SSWWWWWWSS...
..SWWWWWWWWWWS..
.SWWWWWWWWWWWWS.
.SWWKKKKKKKKWWS.
.SWWKKKKKKKKWWS.
.SWWWWWWWWWWWWS.
.SWWWWWWWWWWWWS.
.SWW..WWWW..WWS.
..SW..WWWW..WS..
...SSSSSSSSSS...
....BBBBBBBB....
....BBBBBBBB....
................
................
................
""", {
    '.': (0, 0, 0, 0),
    'S': (51, 65, 85, 255),    # Acero oscuro
    'W': (203, 213, 225, 255), # Visor de plata
    'K': (15, 23, 42, 255),    # Ranura del visor
    'B': (37, 99, 235, 255),   # Cuello de armadura azul
})

# ==============================================================================
# 32. HUIDA (Bota alada para retirada táctica)
# ==============================================================================
save_icon('huida', """
..WW............
.WWWW...........
..WWWW..........
...WWWW.........
....WWWWBBBB....
.....WWBBLLBB...
......BBLLLLBB..
.....BBLLLLLLBB.
....BBLLLLLLLLBB
...BBLLLLLLLLLLB
...BBLLLLLLLLLLB
...BBBBBBBBBBBBB
................
................
................
................
""", {
    '.': (0, 0, 0, 0),
    'W': (255, 255, 255, 255), # Ala blanca
    'B': (69, 26, 3, 255),     # Borde de bota
    'L': (180, 83, 9, 255),    # Cuero de la bota
})

print("\n✅ ¡Los 32 Iconos Pixel Art han sido generados exitosamente en frontend/assets/icons/!")
