import json

# Generador de 400 Preguntas de Java (20 preguntas ordenadas por cada uno de los 20 jefes)
boss_topics = {
    1: ("Sintaxis y Estructura Básica", [
        ("¿Cuál es la firma exacta del método principal de inicio en Java?", ["public static void main(String[] args)", "public void main(String[] args)", "static void main(String args)", "public static int main(String[] args)"], 0, "El punto de entrada oficial es siempre 'public static void main(String[] args)'."),
        ("¿Qué símbolo es indispensable al final de la mayoría de sentencias en Java?", ["Punto (.)", "Dos puntos (:)", "Punto y coma (;)", "Coma (,)"], 2, "El punto y coma ';' finaliza sentencias en Java."),
        ("Si el archivo es 'Heroe.java', ¿cómo debe nombrarse su clase pública?", ["public class Heroe", "public class heroe", "class MiHeroe", "public class Main"], 0, "Debe coincidir exactamente con el nombre del archivo."),
        ("¿Cómo se escribe un comentario de una sola línea en Java?", ["/* Comentario */", "// Comentario", "# Comentario", "<!-- Comentario -->"], 1, "Dos barras '//' crean comentarios de una línea."),
        ("¿Cómo se escribe un comentario de múltiples líneas?", ["/* Comentario */", "<!-- Comentario -->", "## Comentario ##", "{{ Comentario }}"], 0, "Se encierra entre /* y */."),
        ("¿Java distingue entre mayúsculas y minúsculas (case-sensitive)?", ["No, es insensible", "Sí, estrictamente", "Solo en números", "Solo en cadenas"], 1, "Java es estrictamente sensible a mayúsculas y minúsculas."),
        ("¿Qué paquete se importa de manera automática en todos los archivos Java?", ["java.util", "java.io", "java.lang", "java.net"], 2, "java.lang está disponible siempre sin necesidad de importarlo."),
        ("¿Cuál es la convención de nombres recomendada para clases en Java?", ["camelCase", "PascalCase (UpperCamelCase)", "snake_case", "kebab-case"], 1, "Las clases usan PascalCase iniciando con mayúscula."),
        ("¿Cuál de estos identificadores es VÁLIDO en Java?", ["1erNombre", "nombre_completo$", "class", "nombre-usuario"], 1, "Puede contener letras, números, guiones bajos y $ (no puede empezar con número ni ser palabra reservada)."),
        ("¿Qué palabra clave se usa para definir una nueva clase?", ["def", "class", "struct", "module"], 1, "La palabra clave es 'class'."),
        ("¿Qué delimitadores encierran un bloque de código en Java?", ["Paréntesis ( )", "Corchetes [ ]", "Llaves { }", "Comillas \" \""], 2, "Las llaves { } delimitan bloques de código."),
        ("¿Cuál de las siguientes es una palabra reservada en Java?", ["main", "static", "String", "System"], 1, "'static' es una palabra reservada del lenguaje."),
        ("¿Cuál es la extensión de los archivos de código fuente de Java?", [".class", ".java", ".jar", ".jvm"], 1, "Los archivos fuente editables terminan en .java."),
        ("¿Cuál es la extensión de los archivos compilados a Bytecode?", [".class", ".exe", ".bin", ".byte"], 0, "El compilador javac genera archivos .class."),
        ("¿Qué significa 'static' en el método main?", ["Que puede invocarse sin instanciar la clase", "Que nunca cambia de valor", "Que no devuelve nada", "Que es privado"], 0, "Los métodos estáticos pertenecen a la clase y no requieren un objeto para ejecutarse."),
        ("¿Qué contiene el parámetro 'String[] args' en main?", ["Los argumentos de línea de comandos", "La versión de la JVM", "La memoria libre", "El nombre de la computadora"], 0, "Recibe los argumentos pasados al ejecutar el programa."),
        ("¿Se puede tener más de una clase pública en un solo archivo .java?", ["Sí, ilimitadas", "No, máximo una clase pública por archivo", "Solo si no tienen método main", "Solo en paquetes privados"], 1, "Solo puede haber una clase pública por archivo fuente."),
        ("¿Cómo se llama la herramienta oficial que genera documentación desde comentarios /** */?", ["Javadoc", "Javalog", "Javadir", "Javaspec"], 0, "Javadoc genera páginas HTML de documentación."),
        ("¿Qué palabra clave se usa para importar clases de otros paquetes?", ["include", "using", "import", "require"], 2, "Se usa la palabra 'import'."),
        ("¿Cuál es la palabra clave para definir que un método pertenece al punto de entrada sin retorno?", ["void", "null", "empty", "zero"], 0, "'void' indica que el método no produce ningún valor de retorno.")
    ]),

    2: ("Variables y Tipos de Datos Primitivos", [
        ("¿Cuántos tipos de datos primitivos existen en Java?", ["4", "6", "8", "10"], 2, "Java cuenta con exactamente 8 tipos primitivos."),
        ("¿Cuál de los siguientes NO es un tipo primitivo en Java?", ["int", "boolean", "String", "double"], 2, "'String' es una clase u objeto de referencia, no un primitivo."),
        ("¿Qué tipo primitivo se usa para almacenar valores verdadero o falso?", ["bool", "boolean", "binary", "bit"], 1, "En Java la palabra clave es 'boolean'."),
        ("¿Cuántos bits ocupa el tipo primitivo 'byte' en Java?", ["8 bits", "16 bits", "32 bits", "64 bits"], 0, "Un 'byte' ocupa 8 bits (-128 a 127)."),
        ("¿Cuántos bits ocupa el tipo primitivo 'int' en Java?", ["8 bits", "16 bits", "32 bits", "64 bits"], 2, "Un 'int' ocupa 32 bits en memoria."),
        ("¿Cuántos bits ocupa el tipo primitivo 'long' en Java?", ["32 bits", "64 bits", "128 bits", "16 bits"], 1, "Un 'long' ocupa 64 bits en memoria."),
        ("¿Qué sufijo se debe agregar a un literal numérico largo de tipo long?", ["F", "L (o l)", "D", "B"], 1, "Se agrega 'L' al final (ejemplo: 5000000000L)."),
        ("¿Qué tipo primitivo representa números decimales de precisión simple (32 bits)?", ["double", "float", "decimal", "real"], 1, "'float' representa punto flotante de 32 bits."),
        ("¿Qué sufijo es obligatorio al asignar un literal decimal a una variable float?", ["F (o f)", "D", "L", "S"], 0, "Los literales decimales son double por defecto, por lo que float requiere 'f' (ej: 3.14f)."),
        ("¿Qué tipo primitivo representa números decimales de doble precisión (64 bits)?", ["float", "double", "decimal", "long"], 1, "'double' es el tipo estándar de 64 bits para decimales."),
        ("¿Qué tipo primitivo se usa para almacenar un único carácter Unicode?", ["string", "char", "character", "byte"], 1, "'char' almacena un único carácter de 16 bits Unicode."),
        ("¿Cómo se delimitan los literales de tipo 'char' en Java?", ["Comillas dobles \" \"", "Comillas simples ' '", "Acentos graves ` `", "Paréntesis ( )"], 1, "Los caracteres char usan comillas simples (ejemplo: 'A')."),
        ("¿Cuál es el valor por defecto de una variable numérica primitiva de instancia?", ["null", "0", "undefined", "-1"], 1, "Las variables numéricas de instancia se inicializan en 0 por defecto."),
        ("¿Cuál es el valor por defecto de un 'boolean' de instancia en Java?", ["true", "false", "null", "0"], 1, "El valor por defecto de un boolean es 'false'."),
        ("¿Cómo se declara e inicializa una variable entera en Java?", ["int edad = 20;", "edad = 20 as int;", "var int edad = 20;", "integer edad = 20;"], 0, "La sintaxis es: tipo nombre = valor; (ej: int edad = 20;)."),
        ("¿Qué palabra clave hace que una variable sea constante (inmutable)?", ["const", "final", "static", "immutable"], 1, "'final' impide que la variable sea reasignada."),
        ("¿Cuál es la convención para nombrar constantes en Java?", ["camelCase", "MAYUSCULAS_CON_GUION_BAJO", "PascalCase", "lowercase"], 1, "Se nombran en mayúsculas con guiones bajos (ej: MAX_VIDA)."),
        ("¿Qué palabra clave introducida en Java 10 permite inferencia de tipos locales?", ["auto", "var", "let", "def"], 1, "'var' permite que el compilador deduzca el tipo de la variable local."),
        ("¿Se puede asignar un valor 'double' directamente a un 'int' sin casteo?", ["Sí, automáticamente", "No, genera error de pérdida de precisión", "Solo si es positivo", "Solo si vale cero"], 1, "Requiere casteo explícito: (int) miDouble."),
        ("¿Cómo se realiza un casteo explícito (type casting) de double a int?", ["(int) valorDouble", "int(valorDouble)", "valorDouble.toInt()", "valorDouble as int"], 0, "Se antepone el tipo entre paréntesis: (int) valorDouble.")
    ]),

    3: ("Operadores Aritméticos y Lógicos", [
        ("¿Cuál es el resultado de la operación 19 % 4 en Java?", ["4", "3", "4.75", "1"], 1, "El operador '%' es el residuo (módulo): 19 / 4 = 4 con residuo de 3."),
        ("¿Qué hace el operador de pre-incremento ++x?", ["Incrementa x después de usar su valor", "Incrementa x antes de evaluar la expresión", "Multiplica x por dos", "Eleva x al cuadrado"], 1, "++x primero suma 1 a la variable y luego entrega el nuevo valor."),
        ("Si int x = 5; int y = x++; ¿cuál es el valor de 'y'?", ["5", "6", "7", "4"], 0, "El post-incremento (x++) entrega primero el valor actual (5) y luego incrementa x a 6."),
        ("¿Qué operador representa el 'Y' lógico (AND) con cortocircuito?", ["&", "&&", "AND", "/\\"], 1, "'&&' es el operador lógico AND."),
        ("¿Qué operador representa el 'O' lógico (OR) con cortocircuito?", ["|", "||", "OR", "\\/"], 1, "'||' es el operador lógico OR."),
        ("¿Qué operador invierte el valor booleano (NOT lógico)?", ["~", "!", "NOT", "^"], 1, "'!' es la negación lógica (ej: !true es false)."),
        ("¿Cuál es el resultado de (true || false) && (!false)?", ["true", "false", "null", "Error"], 0, "(true || false) es true; (!false) es true; true && true es true."),
        ("¿Qué significa la asignación compuesta: x += 5?", ["x = 5;", "x = x + 5;", "x = x * 5;", "x == 5"], 1, "x += 5 equivale exactamente a x = x + 5;"),
        ("¿Cuál es el resultado de la división entera 7 / 2 en Java?", ["3.5", "3", "4", "3.0"], 1, "La división entre dos enteros trunca la parte decimal, dando 3."),
        ("Para obtener 3.5 al dividir 7 entre 2, ¿cómo debe escribirse?", ["7 / 2", "7.0 / 2", "(int) 7 / 2", "div(7, 2)"], 1, "Al menos uno de los operandos debe ser decimal: 7.0 / 2 da 3.5."),
        ("¿Qué operador compara si dos valores primitivos son iguales?", ["=", "==", "===", "equals"], 1, "'==' compara igualdad de valores en primitivos."),
        ("¿Qué operador evalúa si dos valores son diferentes?", ["!=", "<>", "not ==", "!=="], 0, "'!=' evalúa desigualdad."),
        ("¿Qué operador se conoce como el operador ternario en Java?", ["if-else", "? :", "??", "::"], 1, "El operador ternario se escribe: condición ? valorSiTrue : valorSiFalse."),
        ("En la expresión a = (x > 10) ? 1 : 2; si x vale 5, ¿cuánto vale 'a'?", ["1", "2", "10", "5"], 1, "Como 5 > 10 es falso, se toma el segundo valor: 2."),
        ("¿Qué significa que un operador lógico sea de 'cortocircuito'?", ["Que causa un error de sistema", "Que no evalúa el segundo operando si el primero ya determina el resultado", "Que corre más rápido siempre", "Que solo opera con enteros"], 1, "En '&&', si el primer operando es false, el segundo no se evalúa."),
        ("¿Cuál es el resultado de: 10 + 2 * 3 según la precedencia de operadores?", ["36", "16", "26", "15"], 1, "La multiplicación tiene mayor precedencia: 2 * 3 = 6; 10 + 6 = 16."),
        ("¿Cómo se puede forzar que una suma se ejecute antes que una multiplicación?", ["Usando corchetes [ ]", "Usando paréntesis ( )", "Con llaves { }", "Con comas"], 1, "Los paréntesis ( ) tienen la máxima precedencia."),
        ("¿Qué operador realiza un desplazamiento de bits a la izquierda?", ["<<", ">>", ">>>", "<="], 0, "'<<' desplaza los bits hacia la izquierda."),
        ("¿Cuál es el resultado de x -= 3 si x valía 10?", ["13", "7", "3", "-7"], 1, "x = 10 - 3 = 7."),
        ("¿Cuál es el resultado de 15 % 5?", ["3", "0", "1", "5"], 1, "15 entre 5 es 3 exacto, el residuo es 0.")
    ]),

    4: ("Salida Estándar y Concatenación", [
        ("¿Qué instrucción imprime texto en consola con un salto de línea al final?", ["System.out.print()", "System.out.println()", "Console.writeLine()", "echo()"], 1, "System.out.println() añade un salto de línea tras el mensaje."),
        ("¿Qué instrucción imprime texto en consola SIN dar salto de línea?", ["System.out.print()", "System.out.println()", "System.out.write()", "print.out()"], 0, "System.out.print() deja el cursor en la misma línea."),
        ("¿Qué imprime: System.out.println(\"A\" + 1 + 2);?", ["A3", "A12", "Error", "A1+2"], 1, "Se evalúa de izquierda a derecha: \"A\" + 1 -> \"A1\" + 2 -> \"A12\"."),
        ("¿Qué imprime: System.out.println(1 + 2 + \"A\");?", ["3A", "12A", "Error", "A3"], 0, "1 + 2 es suma numérica (3) y luego se concatena con \"A\" dando \"3A\"."),
        ("¿Qué secuencia de escape representa un salto de línea dentro de un String?", ["\\t", "\\n", "\\b", "\\r"], 1, "'\\n' representa una nueva línea (newline)."),
        ("¿Qué secuencia de escape inserta una tabulación horizontal?", ["\\n", "\\t", "\\s", "\\h"], 1, "'\\t' inserta un tabulador."),
        ("¿Cómo se incluye una comilla doble dentro de un String sin cerrarlo?", ["\\\"", "/\"", "\"\"", "\\'"], 0, "Se escapa con barra invertida: \\\"."),
        ("¿Qué método de System.out permite imprimir con formato tipo printf de C?", ["System.out.printf()", "System.out.format()", "Ambas opciones son correctas", "Ninguna"], 2, "Tanto printf() como format() imprimen con especificadores de formato."),
        ("En System.out.printf(), ¿qué especificador se usa para un número entero?", ["%f", "%d", "%s", "%c"], 1, "'%d' especifica un número entero decimal."),
        ("En System.out.printf(), ¿qué especificador se usa para una cadena de texto?", ["%d", "%s", "%t", "%c"], 1, "'%s' especifica una cadena (String)."),
        ("En System.out.printf(), ¿qué especificador se usa para un número flotante/double?", ["%d", "%f", "%s", "%b"], 1, "'%f' especifica un número con punto flotante."),
        ("¿Qué objeto representa la salida estándar de errores en Java?", ["System.in", "System.err", "System.out", "System.log"], 1, "System.err es el flujo estándar de errores (suele mostrar texto rojo)."),
        ("¿Qué objeto representa la entrada estándar por teclado en Java?", ["System.in", "System.input", "System.read", "System.keyboard"], 0, "System.in representa el flujo estándar de entrada."),
        ("¿Qué clase del paquete java.util se usa frecuentemente para leer datos de System.in?", ["Reader", "Scanner", "InputGrabber", "ConsoleReader"], 1, "La clase Scanner permite leer enteros, decimales y líneas de texto."),
        ("¿Qué imprime System.out.println(5 == 5);?", ["5", "true", "false", "null"], 1, "Evalúa la expresión booleana e imprime 'true'."),
        ("¿Qué imprime System.out.println(\"Java\".length());?", ["4", "5", "3", "Error"], 0, "El método length() de la cadena \"Java\" retorna 4."),
        ("¿Qué secuencia de escape representa la barra invertida literal?", ["\\\\", "//", "\\b", "\\0"], 0, "'\\\\' imprime una única barra invertida."),
        ("¿Qué imprime System.out.println(\"Hola \" + \"Mundo\");?", ["HolaMundo", "Hola Mundo", "Error de tipos", "null"], 1, "Concatena ambas cadenas resultando en 'Hola Mundo'."),
        ("¿Qué imprime System.out.println(10 > 20);?", ["true", "false", "10", "20"], 1, "10 no es mayor que 20, por lo que imprime 'false'."),
        ("¿Cuál es el resultado de imprimir System.out.println(); sin argumentos?", ["Error", "Imprime una línea vacía (solo el salto de línea)", "Imprime null", "Imprime 0"], 1, "Solo emite un salto de línea en la consola.")
    ]),

    5: ("Estructuras Condicionales (if - else)", [
        ("¿Qué tipo de dato DEBE retornar la condición dentro del 'if' en Java?", ["int", "boolean", "String", "Cualquier número"], 1, "La condición de un 'if' en Java DEBE ser estrictamente de tipo boolean."),
        ("En: int x = 10; if (x > 15) { ... } else { ... } ¿Qué bloque se ejecuta?", ["El bloque if", "El bloque else", "Ambos", "Ninguno"], 1, "Como 10 > 15 es false, se ejecuta el bloque 'else'."),
        ("¿Cuál es la sintaxis correcta para comprobar múltiples condiciones consecutivas?", ["else if", "elif", "elseif", "then if"], 0, "En Java se escribe 'else if' como dos palabras separadas."),
        ("¿Es obligatorio que todo bloque 'if' tenga una sección 'else'?", ["Sí, siempre", "No, el bloque else es totalmente opcional", "Solo si hay variables", "Solo en métodos void"], 1, "El bloque 'else' es opcional."),
        ("Si un bloque 'if' contiene solo una sentencia, ¿son obligatorias las llaves { }?", ["Sí, siempre", "No, pero es una buena práctica usarlas", "Solo si es un return", "Solo en bucles"], 1, "No son obligatorias para una sola línea, pero es muy recomendado usarlas."),
        ("¿Qué imprime: int a = 5; if (a == 5) System.out.print(\"A\"); else System.out.print(\"B\");?", ["A", "B", "AB", "Error"], 0, "Como a == 5 es true, imprime 'A'."),
        ("¿Qué operador relacional evalúa si un número es menor o igual a otro?", ["<=", "=<", "<==", "min"], 0, "'<=' representa menor o igual."),
        ("¿Qué operador relacional evalúa si un número es mayor o igual a otro?", [">=", "=>", ">>", "max"], 0, "'>=' representa mayor o igual."),
        ("Dada la condición: if (x > 0 && x < 10), ¿cuándo es verdadera?", ["Cuando x está entre 1 y 9", "Cuando x es menor que 0", "Cuando x es 10", "Siempre"], 0, "Ambas condiciones deben cumplirse: x debe ser mayor que 0 y menor que 10."),
        ("Dada la condición: if (x < 0 || x > 100), ¿cuándo es verdadera?", ["Cuando x está fuera del rango [0, 100]", "Cuando x es 50", "Solo si x es cero", "Nunca"], 0, "Es verdadera si x es negativo O si es mayor que 100."),
        ("¿Se pueden anidar sentencias 'if' dentro de otros bloques 'if'?", ["No, está prohibido", "Sí, a cualquier nivel de anidamiento", "Solo hasta 2 niveles", "Solo con switch"], 1, "Se pueden anidar condicionales sin restricción."),
        ("¿Qué ocurre si escribes if (x = 5) en Java siendo x un entero?", ["Se asigna 5 y evalúa true", "Error de compilación ('Type mismatch: cannot convert from int to boolean')", "Se evalúa false", "Se lanza una excepción"], 1, "En Java '=' es asignación y no retorna boolean, causando error de compilación."),
        ("¿Qué ocurre si escribes if (b = true) siendo b una variable boolean?", ["Error de compilación", "Asigna true a b y la condición resulta verdadera", "Evalúa falso", "Se cuelga el programa"], 1, "Como b es boolean, la asignación retorna true y entra al bloque if (por eso se debe usar ==)."),
        ("¿Qué imprime: if (true) System.out.print(\"1\"); if (false) System.out.print(\"2\");?", ["1", "2", "12", "Error"], 0, "Solo la primera condición es verdadera, por lo que imprime '1'."),
        ("¿Cuál es la forma más limpia de verificar si un booleano 'esHeroe' es falso?", ["if (!esHeroe)", "if (esHeroe == false)", "Ambas son válidas, pero !esHeroe es más idiomática", "if (esHeroe != true)"], 2, "Ambas funcionan, pero '!esHeroe' es la convención estándar en Java."),
        ("En un if-else if-else en cadena, ¿cuántos bloques se pueden ejecutar como máximo?", ["Todos los que coincidan", "Exactamente uno (el primero cuya condición sea true)", "Dos", "Ninguno si hay else"], 1, "En cuanto una condición coincide, se ejecuta su bloque y se ignora el resto."),
        ("¿Qué sentencia se ejecuta si ninguna de las condiciones de un if-else if resulta verdadera?", ["El bloque 'else' (si existe)", "La primera sentencia de nuevo", "El programa termina", "Se lanza un error"], 0, "El bloque 'else' actúa como la rama por defecto."),
        ("¿Qué valor tiene 'resultado' tras: int x = 3; String resultado = (x % 2 == 0) ? \"Par\" : \"Impar\";?", ["Par", "Impar", "null", "Error"], 1, "3 % 2 es 1, no es igual a 0, por lo que retorna 'Impar'."),
        ("¿Qué operador tiene mayor precedencia: operadores relacionales (> , <) o lógicos (&&, ||)?", ["Los relacionales se evalúan antes que los lógicos", "Los lógicos van primero", "Tienen igual precedencia", "Depende del compilador"], 0, "Los relacionales (> , <, ==) tienen mayor precedencia que los operadores lógicos."),
        ("¿Qué imprime: if (5 > 3) { if (2 > 4) System.out.print(\"A\"); else System.out.print(\"B\"); }?", ["A", "B", "AB", "Nada"], 1, "Entra al primer if (5>3 es true), y en el segundo (2>4 es false) cae en el else imprimiendo 'B'.")
    ])
}

print(f'Topics 1 to 5 defined: {len(boss_topics)} bosses.')
